### ISSUE TITLE
If there is no scrollable node it results in an error

### ISSUE THREAD

**Issue by ferdinandsalis** [paypal/react-kadabra#75]
- `react-kadabra` version: 1.0.0-beta.7
- `node` version: 8.1.4
- `npm` (or `yarn`) version: 5.3.0

**What I did:**
Clicked on the button that opens the list.

**What happened:**
```
Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at scrollIntoView (utils.js:70)
    at Autocomplete.maybeScrollToHighlightedElement (autocomplete.js:378)
    at Autocomplete.<anonymous> (autocomplete.js:84)
```

I tried to reproduce here but since [codesandbox](https://codesandbox.io/s/yPp1XZnDR) has a scrollable node at some point the error does not occur. However in local project I can reproduce. Setting the `List` Container to a `maxHeight` lower than the height of the contained elements 'fixes' the bug. If you need a repo of the actual behaviour let me know.

**Problem description:**
If there is no scrollable node it results in an error

**Suggested solution:**
I guess we should stop traversing the dom at the component boundary and if the `scrollHeight` equals `clientHeight` we do not need to scroll into view.

PS. I am love the flexibility the api provides. Great work!

**Comment by kentcdodds** [comment]
Thanks for this! If you could implement a fix that would be super! Feel free to [make a pull request](http://makeapullrequest.com)! 👍

**Comment by ferdinandsalis** [comment]
Will do!

**Comment by ferdinandsalis** [comment]
@kentcdodds I am trying to link my local fork of react-kadabra via `npm link` in the root directory of react-kadabra and `npm link react-kadabra` in my project to test it. However I get the following error `Module not found: Can't resolve 'react-kadabra'` when running the app. Do you have a clue why that is not working? Same goes for just installing the local package via `npm install`.

On another note I haven't done much testing with react so excuse my ignorance. The only test seems to pass although the apparent bug. How would we test this?

**Comment by ferdinandsalis** [comment]
Resolved the apove. Sorry for the noise. I had some linting errors and this failed the build …

**Comment by kentcdodds** [comment]
Don't worry about tests yet. I'll add tests when the API has solidified before we do the official release :smile:
